// Generated by Selenium IDE
require('chromedriver')
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


describe('Acessando Categorias', function() {
this.timeout(30000)
let driver
let vars

beforeEach(async function() {
  driver = await new Builder().forBrowser('chrome').build()
  vars = {}
})
afterEach(async function() {
  await driver.quit();
})
  it('Acessando Categorias', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Categorias")).click()
    await driver.findElement(By.css(".btn-materia:nth-child(1)")).click()
{
  const element = await driver.findElement(By.css(".btn-materia:nth-child(1)"))
  await driver.actions({ bridge: true }).move({ origin: element }).perform()
}
await driver.findElement(By.css(".btn-materia:nth-child(2)")).click()
await driver.findElement(By.css(".btn-materia:nth-child(3)")).click()
await driver.findElement(By.css(".btn-materia:nth-child(4)")).click()
{
  const element = await driver.findElement(By.css(".btn-materia:nth-child(4)"))
  await driver.actions({ bridge: true }).move({ origin: element }).perform()
}
await driver.findElement(By.css(".btn-materia:nth-child(5)")).click()
await driver.findElement(By.css(".btn-materia:nth-child(6)")).click()
await driver.findElement(By.css(".btn-materia:nth-child(7)")).click()
  })
})
