// Generated by Selenium IDE
require('chromedriver')
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { fazerLogin } = require('./helpers')


describe('Criar Questão Deixando nulls', function() {
this.timeout(30000)
let driver
let vars

beforeEach(async function() {
  driver = await new Builder().forBrowser('chrome').build()
  vars = {}
})
afterEach(async function() {
  await driver.quit();
})
  it('Criar Questão Deixando nulls', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1281, height: 725 })
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("renato@gmail.com")
    await driver.findElement(By.id("senha")).sendKeys("zampa")
    await driver.findElement(By.id("senha")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//*[contains(text(),'Criar Nova Questão')]")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("materia")).sendKeys("Matemática")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("tema")).sendKeys("Soma e Subtração")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("enunciado")).sendKeys("Teste Teste")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.name("altA")).sendKeys("1")
    await driver.findElement(By.name("altB")).click()
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.name("altB")).click()
    await driver.findElement(By.name("altB")).sendKeys("2")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.name("altC")).click()
    await driver.findElement(By.name("altC")).sendKeys("3")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.name("altD")).click()
    await driver.findElement(By.name("altD")).sendKeys("4")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.name("altE")).sendKeys("5")
    await driver.findElement(By.css(".btn")).click()
    await driver.findElement(By.id("correta")).click()
{
  const dropdown = await driver.findElement(By.id("correta"))
  await dropdown.findElement(By.xpath("//option[. = 'C']")).click()
}
await driver.findElement(By.css("option:nth-child(4)")).click()
await driver.findElement(By.css(".btn")).click()
await driver.findElement(By.id("explicacao")).sendKeys("Testessss")
await driver.findElement(By.css(".btn")).click()
  })
})
