// Generated by Selenium IDE
require('chromedriver')
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { fazerLogin } = require('./helpers')

describe('Criar Questão Certo', function () {
  this.timeout(30000)
  let driver

  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
  })

  afterEach(async function () {
    await driver.quit()
  })

  it('Criar Questão Certo', async function () {
    await driver.get('http://localhost:3000/')
    await driver.manage().window().setRect({ width: 1281, height: 725 })


    await driver.findElement(By.linkText('Login')).click()

    const email = await driver.wait(
      until.elementLocated(By.id('email')),
      10000
    )
    await email.sendKeys('renato@gmail.com')

    await driver.findElement(By.id('senha')).sendKeys('zampa', Key.ENTER)

 
    const criarQuestao = await driver.wait(
      until.elementLocated(
        By.xpath("//*[contains(text(),'Criar Nova Questão')]")
      ),
      10000
    )
    await criarQuestao.click()


    await driver.findElement(By.id('materia')).sendKeys('Matemática')
    await driver.findElement(By.id('tema')).sendKeys('Soma e Subtração')
    await driver.findElement(By.id('enunciado')).sendKeys('2 + 2')

    await driver.findElement(By.name('altA')).sendKeys('4')
    await driver.findElement(By.name('altB')).sendKeys('1')
    await driver.findElement(By.name('altC')).sendKeys('2')
    await driver.findElement(By.name('altD')).sendKeys('3')
    await driver.findElement(By.name('altE')).sendKeys('5')

   
    const correta = await driver.findElement(By.id('correta'))
    await correta.findElement(
      By.xpath(".//option[.='A']")
    ).click()

    await driver.findElement(By.id('explicacao')).sendKeys('Teste')

    await driver.findElement(By.css('.btn')).click()
  })
})
