// Generated by Selenium IDE
require('chromedriver')
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const { fazerLogin } = require('./helpers')


describe('Editar Alterando Tudo', function() {
this.timeout(30000)
let driver
let vars

beforeEach(async function() {
  driver = await new Builder().forBrowser('chrome').build()
  vars = {}
})
afterEach(async function() {
  await driver.quit();
})
  it('Editar Alterando Tudo', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1281, height: 725 })
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("renato@gmail.com")
    await driver.findElement(By.id("senha")).sendKeys("zampa")
    await driver.findElement(By.id("senha")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//*[contains(text(),'Editar')]")).click()
    await driver.findElement(By.id("enunciado")).click()
    await driver.findElement(By.id("enunciado")).sendKeys("Qual é a capital da França?\\nteste")
    await driver.findElement(By.id("materia")).click()
    await driver.findElement(By.id("materia")).sendKeys("Geografia teste")
    await driver.findElement(By.id("tema")).click()
    await driver.findElement(By.id("tema")).sendKeys("Europa teste")
    await driver.findElement(By.id("materia")).click()
    await driver.findElement(By.id("materia")).sendKeys("Química")
    await driver.findElement(By.name("altA")).click()
    await driver.findElement(By.name("altA")).sendKeys("Berlim a")
    await driver.findElement(By.name("altB")).click()
    await driver.findElement(By.name("altB")).sendKeys("Madrid a")
    await driver.findElement(By.name("altC")).click()
    await driver.findElement(By.name("altC")).sendKeys("Paris a")
    await driver.findElement(By.name("altD")).click()
    await driver.findElement(By.name("altD")).sendKeys("Roma a")
    await driver.findElement(By.name("altE")).click()
    await driver.findElement(By.name("altE")).sendKeys("Lisboa a")
    await driver.findElement(By.id("correta")).click()
{
  const dropdown = await driver.findElement(By.id("correta"))
  await dropdown.findElement(By.xpath("//option[. = 'D']")).click()
}
await driver.findElement(By.css("option:nth-child(4)")).click()
await driver.findElement(By.id("explicacao")).click()
await driver.findElement(By.id("explicacao")).click()
await driver.findElement(By.id("explicacao")).sendKeys("Paris é a capital e a cidade mais populosa da França. aaa")
await driver.findElement(By.css(".btn")).click()
  })
})
