// Generated by Selenium IDE
require('chromedriver')
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


describe('Editar sem alteracoes', function() {
this.timeout(30000)
let driver
let vars

beforeEach(async function() {
  driver = await new Builder().forBrowser('chrome').build()
  vars = {}
})
afterEach(async function() {
  await driver.quit();
})
  it('Editar sem alteracoes', async function() {
    await driver.get("http://localhost:3000/")
    await driver.findElement(By.linkText("Login")).click()
    await driver.findElement(By.id("email")).click()
    await driver.findElement(By.id("email")).sendKeys("renato@gmail.com")
    await driver.findElement(By.id("senha")).sendKeys("zampa")
    await driver.findElement(By.id("senha")).sendKeys(Key.ENTER)
    await driver.findElement(By.xpath("//*[contains(text(),'Editar')]")).click()
    await driver.findElement(By.css(".btn")).click()
  })
})
