// Generated by Selenium IDE
require('chromedriver')
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')


describe('Errando Questão', function() {
this.timeout(30000)
let driver
let vars

beforeEach(async function() {
  driver = await new Builder().forBrowser('chrome').build()
  vars = {}
})
afterEach(async function() {
  await driver.quit();
})
  it('Errando Questão', async function() {
    await driver.get("http://localhost:3000/")
    await driver.manage().window().setRect({ width: 1281, height: 725 })
    await driver.findElement(By.linkText("Questões")).click()
    await driver.findElement(By.css(".questao:nth-child(1) .opcao:nth-child(1)")).click()
    await driver.findElement(By.css(".questao:nth-child(1) > .btn")).click()
  })
})
