// Generated by Selenium IDE
require('chromedriver')
const { Builder, By, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Login Correto', function () {
  this.timeout(30000)
  let driver

  beforeEach(async function () {
    driver = await new Builder().forBrowser('chrome').build()
  })

  afterEach(async function () {
    await driver.quit()
  })

  it('Login Correto', async function () {
    await driver.get('http://localhost:3000/')
    await driver.manage().window().setRect({ width: 1281, height: 725 })

    
    await driver.findElement(By.linkText('Login')).click()

    
    const email = await driver.wait(
      until.elementLocated(By.id('email')),
      10000
    )
    await email.sendKeys('renato@gmail.com')

    
    const senha = await driver.findElement(By.id('senha'))
    await senha.sendKeys('zampa')

    
    const botao = await driver.findElement(By.css('button[type="submit"], button'))
    await botao.click()
  })
})
